name: 'Check PR for SemVer Label'
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  pull-requests: read
  contents: read

jobs:
  semver-check:
    name: 'Check PR for SemVer Label'
    if: |
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Parse the SemVer label
        id: label
        uses: UKHomeoffice/match-label-action@7a414a71073cd2f67e0e001ab2c4a38177ea01b6 #v1.05
        with:
          labels: minor,major,patch
          mode: singular

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeoffice/semver-calculate-action@vfd7e1629eda3b5d3cd037d4145d49db12a352c8e #2.07
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
