name: 'SemVer Tag on Main Merge'
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  pull-requests: read
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  semver-tag:
    name: 'Tag Repository with SemVer'
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Parse the SemVer label
        id: label
        uses: UKHomeoffice/match-label-action@7a414a71073cd2f67e0e001ab2c4a38177ea01b6 #v1.05
        with:
          labels: minor,major,patch
          mode: singular

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeoffice/semver-calculate-action@fd7e1629eda3b5d3cd037d4145d49db12a352c8e #2.07
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Repository
        uses: UKHomeoffice/semver-tag-action@v7827a80f5e8898a6775928978d37dbc86441b560 #v3.0
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
